### ISSUE TITLE
CuteEntityManager

### ISSUE THREAD

**Issue by mwallnoefer** [Professi/cuteentitymanager#1]
This seems to be a neat alternative to QxORM/QxEntityEditor which seems much more complicated and heavier in usage.

Is this project still alive (on Redmine I find the following commit https://synlos.net/redmine/projects/entitymanager/repository/27/revisions/6639f988438db3d211c1121ceedede47f0b6e808/diff not present on GitHub)?
Does it provide automatised entity class generation like QxEntityEditor?

**Comment by Professi** [comment]
> This seems to be a neat alternative to QxORM/QxEntityEditor which seems much more complicated and heavier in usage.


Yeah. That was the reason, that I wrote the "CuteEntityManager".


> Is this project still alive (on Redmine I find the following commit https://synlos.net/redmine/projects/entitymanager/repository/27/revisions/6639f988438db3d211c1121ceedede47f0b6e808/diff not present on GitHub)?

Oh. Thanks for the hint. I pushed the last commits. Never thought that anyone would use it on Github. :)
Last months there was no time for this project. So its something between "dead" and "alive". If there would be serious bugs, then I would fix them.

> Does it provide automatised entity class generation like QxEntityEditor?

Nope. I'm not a big fan of generating database schema from code and I hadn't time for this job. :(
